"""initial schema

Revision ID: 4b1f8951f276
Revises:
Create Date: 2026-08-30 11:29:03.511542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b1f8951f276"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "stocks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column(
            "sector",
            sa.Enum(
                "FINANCIALS",
                "IT",
                "DEFENCE",
                "RENEWABLES",
                "PHARMA_HEALTHCARE",
                "AUTO",
                "CHEM_METALS_ENG",
                "FMCG",
                "INFRA_REALTY",
                "POWER_TD",
                "TRADITIONAL_POWER",
                "TELECOM",
                "CONSUMER_RETAIL",
                "MISC",
                name="sector",
            ),
            nullable=False,
        ),
        sa.Column("sub_sector", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "ticker", name="uq_stock_user_ticker"),
    )
    op.create_index(op.f("ix_stocks_user_id"), "stocks", ["user_id"], unique=False)
    op.create_table(
        "research_notes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stock_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_date", sa.Date(), nullable=False),
        sa.Column(
            "call",
            sa.Enum("BUY", "ACCUMULATE", "HOLD", "WAIT_AND_BUY", "SELL", name="call_type"),
            nullable=False,
        ),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("catalysts", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("risks", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("target_1w", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_1w_note", sa.Text(), nullable=True),
        sa.Column("target_1_3m", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_1_3m_note", sa.Text(), nullable=True),
        sa.Column("target_1_3y", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_1_3y_note", sa.Text(), nullable=True),
        sa.Column("technical_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_notes_stock_id"), "research_notes", ["stock_id"], unique=False
    )
    op.create_index(op.f("ix_research_notes_user_id"), "research_notes", ["user_id"], unique=False)
    op.create_table(
        "brokerage_calls",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("research_note_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.String(length=128), nullable=False),
        sa.Column("rating", sa.String(length=64), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("call_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_note_id"],
            ["research_notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brokerage_calls_research_note_id"),
        "brokerage_calls",
        ["research_note_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_brokerage_calls_user_id"), "brokerage_calls", ["user_id"], unique=False
    )
    op.create_table(
        "trade_setups",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stock_id", sa.Uuid(), nullable=False),
        sa.Column("research_note_id", sa.Uuid(), nullable=True),
        sa.Column("scenario", sa.String(length=64), nullable=False),
        sa.Column("entry_zone_low", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("entry_zone_high", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum("SWING", "POSITIONAL", "LONG_TERM", name="timeframe"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "TRIGGERED", "INVALIDATED", "CLOSED", name="setup_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["research_note_id"],
            ["research_notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trade_setups_research_note_id"), "trade_setups", ["research_note_id"], unique=False
    )
    op.create_index(op.f("ix_trade_setups_stock_id"), "trade_setups", ["stock_id"], unique=False)
    op.create_index(op.f("ix_trade_setups_user_id"), "trade_setups", ["user_id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stock_id", sa.Uuid(), nullable=False),
        sa.Column("setup_id", sa.Uuid(), nullable=True),
        sa.Column(
            "broker", sa.Enum("ZERODHA", "GROWW", "OTHER", name="broker_name"), nullable=False
        ),
        sa.Column("side", sa.Enum("BUY", "SELL", name="trade_side"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["setup_id"],
            ["trade_setups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_setup_id"), "trades", ["setup_id"], unique=False)
    op.create_index(op.f("ix_trades_stock_id"), "trades", ["stock_id"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_stock_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_setup_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_trade_setups_user_id"), table_name="trade_setups")
    op.drop_index(op.f("ix_trade_setups_stock_id"), table_name="trade_setups")
    op.drop_index(op.f("ix_trade_setups_research_note_id"), table_name="trade_setups")
    op.drop_table("trade_setups")
    op.drop_index(op.f("ix_brokerage_calls_user_id"), table_name="brokerage_calls")
    op.drop_index(op.f("ix_brokerage_calls_research_note_id"), table_name="brokerage_calls")
    op.drop_table("brokerage_calls")
    op.drop_index(op.f("ix_research_notes_user_id"), table_name="research_notes")
    op.drop_index(op.f("ix_research_notes_stock_id"), table_name="research_notes")
    op.drop_table("research_notes")
    op.drop_index(op.f("ix_stocks_user_id"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
